### ISSUE TITLE
Usage of `log_odds_ratio.py` 

### ISSUE THREAD

**Issue by guanqun-yang** [kornosk/log-odds-ratio#1]
I came across this repository after reading your [NAACL '21 paper](https://aclanthology.org/2021.naacl-main.376.pdf). It seems to be a simple method that captures the important words in the text dataset. But I have questions in two aspects: theory and usage.

## Theory
- Does the `log-odds-ratio` method constrain the number of classes in the dataset? From what I could see, it would be difficult to apply this approach if I have a dataset with more than 3 classes (or equivalently, this method is only applicable to 2/3 class dataset).
- In your NAACL '21 paper, you mentioned the following. But I could not see what the score is compared to when you refer to "higher" and "lower". Is there a pre-specified threshold?
> A higher score indicates more significance .... A lower score means ....
- In your NAACL '21 paper, you mentioned the following. What is this "sensitivity analysis"? Did you try to increase `k` to investigate its influence on the classification performance?
> Based on a sensitivity analysis, we set k=10 to extract the top-10 significant words...

## Usage
- The format of corpus i, corpus j, and background corpus is not provided in the `README.md`. Are they simply sentences separated by `\n` or some special format is required?

**Comment by kornosk** [comment]
@guanqun-yang Thank you for your interest!

## Theory
1. It originally works for only 2 classes (as this script only works for 2 classes too). In the paper, we propose a way to apply output from this script to 3 classes in Section 3.1. I think it is still an open question on how to make it works for N classes. The easiest way is to make use of this technique by considering class-A vs. class-not-A, then class-B vs. class-not-B, then class-C vs. class-not-C, so on.
2. I think the paper means the Z-score of each token computed by `log-odds-ratio` as you can see in Equation 3. Also, if you prefer to see [the code](https://github.com/kornosk/log-odds-ratio/blob/master/log_odds_ratio.py#L206), the output tokens are ranked by Z-score from higher to lower.
3. `sensitivity analysis` is a term meaning a study of the uncertainty of the output of the model based on different circumstances. Basically, it means we tried several experiments with different settings and conclude that k=10 is a reasonable number.

## Usage
1. This is a good question. You can put raw text data. The script will do some simple preprocessing, tokenization, and stuff for you. The tokenization is based on space and `\n`.
2. Note that for now, it only supports English.

Hope this helps!

**Comment by guanqun-yang** [comment]
@kornosk Thanks for the prompt reply. Really appreciate it! 
I have got your code running and it seems that the code output sensible outputs.
